sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t pwcho/lab8 .

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multifib"
  env: "Mmltifib-env"
  bucket_name: "elasticbeanstalk-us-east-2-862524626250"
  bucket_path: "multifib"
  edge: true
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
