FROM node:17.3.0-alpine as build
WORKDIR /usr/local/app
COPY ./ /usr/local/app/
RUN npm install
RUN npm run build

FROM nginx:1.21-alpine
COPY --from=build /usr/local/app/dist/pwcho-zad1-frontend /usr/share/nginx/html
EXPOSE 80
